FROM debian:buster-slim

RUN wget --content-disposition https://packagecloud.io/ato/deb/packages/debian/buster/go-bin-deb_0.0.19+gx6_amd64.deb/download.deb -O go-bin-deb.deb && \
    dpkg -i go-bin-deb.deb && \
    rm -f go-bin-deb.deb

RUN apt-get update && apt-get install -y \
    git curl wget unzip \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    crossbuild-essential-arm64 && \
    dpkg --add-architecture arm64 && \
    rm -rf /var/lib/apt/lists/*
