FROM debian:bullseye-slim

ARG TARGETARCH

RUN apt-get update && apt-get install -y \
    git curl wget unzip jq \
    build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN wget --content-disposition https://packagecloud.io/atotto/debian-utils/packages/any/any/go-bin-deb_0.0.19+gx11_${TARGETARCH}.deb/download.deb -O dpkg.deb && dpkg -i dpkg.deb && rm -f dpkg.deb
RUN curl -sL "https://dl.google.com/go/$(curl -s https://go.dev/dl/?mode=json | jq -r '.[0].version').linux-${TARGETARCH}.tar.gz" | tar xz -C /usr/local && ln -sf /usr/local/go/bin/go /usr/local/bin/go && ln -sf /usr/local/go/bin/gofmt /usr/local/bin/gofmt
RUN curl -sL "https://github.com/dominikh/go-tools/releases/download/$(curl -s https://api.github.com/repos/dominikh/go-tools/releases/latest | jq '.tag_name' -r)/staticcheck_linux_${TARGETARCH}.tar.gz" | tar xz staticcheck --strip=1 && mv staticcheck /usr/local/bin/
RUN wget -O /usr/local/bin/shfmt https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_${TARGETARCH} && chmod +x /usr/local/bin/shfmt
